# Generated by Django 6.0.7 on 2026-07-10 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('dni', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColorCelular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCelular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MarcaModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: USD', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Celular',
            fields=[
                ('numero_serie', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('precio_compra', models.FloatField()),
                ('proveedor', models.CharField(max_length=200)),
                ('observacion', models.CharField(blank=True, max_length=2000, null=True)),
                ('id_color', models.ForeignKey(db_column='id_color', on_delete=django.db.models.deletion.PROTECT, to='control_stock.colorcelular')),
                ('id_estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.PROTECT, to='control_stock.estadocelular')),
            ],
        ),
        migrations.CreateModel(
            name='LogCelular',
            fields=[
                ('dni', models.AutoField(db_column='dni', primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=4000)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('id_celular', models.ForeignKey(db_column='id_celular', on_delete=django.db.models.deletion.CASCADE, to='control_stock.celular')),
            ],
        ),
        migrations.CreateModel(
            name='ModeloCelular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.IntegerField(help_text='Capacidad en GB')),
                ('id_marca', models.ForeignKey(db_column='id_marca', on_delete=django.db.models.deletion.CASCADE, to='control_stock.marcamodelo')),
            ],
        ),
        migrations.AddField(
            model_name='celular',
            name='id_modelo',
            field=models.ForeignKey(db_column='id_modelo', on_delete=django.db.models.deletion.PROTECT, to='control_stock.modelocelular'),
        ),
        migrations.AddField(
            model_name='celular',
            name='id_moneda',
            field=models.ForeignKey(db_column='id_moneda', on_delete=django.db.models.deletion.PROTECT, to='control_stock.moneda'),
        ),
        migrations.CreateModel(
            name='ReservaCelular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=2000, null=True)),
                ('id_celular', models.ForeignKey(db_column='id_celular', on_delete=django.db.models.deletion.CASCADE, to='control_stock.celular')),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='control_stock.cliente')),
                ('id_estado_reserva', models.ForeignKey(db_column='id_estado_reserva', on_delete=django.db.models.deletion.PROTECT, to='control_stock.estadoreserva')),
                ('id_vendedor', models.ForeignKey(db_column='id_vendedor', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VentaCelular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_venta', models.FloatField()),
                ('observaciones', models.CharField(blank=True, max_length=2000, null=True)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('id_celular', models.ForeignKey(db_column='id_celular', on_delete=django.db.models.deletion.CASCADE, to='control_stock.celular')),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, to='control_stock.cliente')),
                ('id_moneda', models.ForeignKey(db_column='id_moneda', on_delete=django.db.models.deletion.PROTECT, to='control_stock.moneda')),
                ('id_vendedor', models.ForeignKey(db_column='id_vendedor', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
