# Generated by Django 6.0.7 on 2026-07-11 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_stock', '0002_logcelular_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacelular',
            name='id_moneda',
            field=models.ForeignKey(blank=True, db_column='id_moneda', null=True, on_delete=django.db.models.deletion.PROTECT, to='control_stock.moneda'),
        ),
        migrations.AddField(
            model_name='reservacelular',
            name='precio_venta',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
