# Generated by Django 6.0.7 on 2026-07-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_stock', '0003_reservacelular_id_moneda_reservacelular_precio_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelocelular',
            name='nombre',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
